[package]
name = "rawtp-ebpf"
version = "0.1.0"
edition.workspace = true

[dependencies]
rawtp-common = { path = "../rawtp-common" }

aya-ebpf = { workspace = true }
aya-log-ebpf = { workspace = true }

[build-dependencies]
which = { workspace = true }

[[bin]]
name = "rawtp"
path = "src/main.rs"
